apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres
spec:
  ingress:
    - ports:
        - port: 5432
          protocol: TCP
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
    - Ingress